version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - echo pre_build

  build:
    commands:
      - echo sync CFN templates to S3 Bucket
      - echo ${BUCKET}
      - aws s3 sync samples/cloudformation/ s3://${BUCKET}/cfn/ --acl public-read
      
      
